/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Translation } from './types';

export const translations: Record<'en' | 'ta', Translation> = {
  en: {
    appName: 'NALAM THEDI LAB',
    tagline: 'Affordable AI Screening for Rural Women',
    startScreening: 'Start Screening',
    viewReports: 'View Previous Reports',
    about: 'About Nalam Thedi',
    aboutText: 'Nalam Thedi Labs provides AI-powered screening tools to help rural healthcare workers identify health risks early.',
    alignStrip: 'Align strip inside the box and capture clearly',
    capture: 'Capture',
    processing: 'Processing Image...',
    results: 'Screening Results',
    urineParameters: 'Urine Parameters',
    glucose: 'Glucose',
    protein: 'Protein',
    leukocytes: 'Leukocytes',
    nitrite: 'Nitrite',
    hemoglobin: 'Hemoglobin',
    hbValue: 'Hb Value',
    interpretation: 'Interpretation',
    doctorPriority: 'Doctor Visit Priority',
    explanation: 'Explanation',
    downloadPdf: 'Download Report',
    shareWhatsapp: 'Share via WhatsApp',
    returnHome: 'Return to Home',
    routineVisit: 'Routine Visit',
    visitPHC7Days: 'Visit PHC within 7 days',
    immediateReferral: 'Immediate PHC Referral',
    disclaimer: 'AI-based screening tool. Not a confirmed laboratory diagnosis.',
    normal: 'Normal',
    mild: 'Mild',
    high: 'High',
    negative: 'Negative',
    positive: 'Positive',
    mildAnemia: 'Mild Anemia',
    moderateAnemia: 'Moderate Anemia',
    severeAnemia: 'Severe Anemia',
    enterPhone: 'Enter WhatsApp Number',
    phonePlaceholder: 'e.g. 9876543210',
    continue: 'Continue',
    previousReports: 'Previous Reports',
    noReports: 'No previous reports found.',
    patientDetails: 'Patient Details',
    patientName: 'Patient Name',
    age: 'Age',
    village: 'Village / Town',
    namePlaceholder: 'Enter full name',
    agePlaceholder: 'Enter age',
    villagePlaceholder: 'Enter village name',
    parameter: 'Parameter',
    result: 'Result',
    unit: 'Unit',
    refRange: 'Ref. Range',
    labReport: 'Laboratory Screening Report',
    selectSource: 'Select Source',
    useCamera: 'Use Camera',
    uploadImage: 'Upload Image',
    lowRisk: 'LOW RISK',
    moderateRisk: 'MODERATE RISK',
    highRisk: 'HIGH RISK',
    criticalRisk: 'CRITICAL',
    aiConfidence: 'AI Confidence Score',
    modelVersion: 'Model Version',
    datasetSize: 'Validated Dataset Size',
    whyThisDecision: 'Why this decision?',
    testQualityCheck: 'Test Quality Check',
    imageQuality: 'Image Quality',
    detectionConfidence: 'Strip Detection Confidence',
    lightingCalibration: 'Lighting Calibration',
    passed: 'Passed',
    failed: 'Failed',
    recommendedAction: 'Recommended Action',
    visitPHC24h: 'Visit PHC within 24 hours',
    repeatUrineTest: 'Repeat urine test',
    confirmatoryHbTest: 'Confirmatory Hb test',
    ironSupplements: 'Iron supplementation if confirmed',
    doctorConsultationMandatory: 'Doctor consultation mandatory for high-risk',
    screeningLocation: 'Screening Location',
    screenedBy: 'Screened By',
    deviceId: 'Device ID',
    offlineStatus: 'Offline Mode Status',
    enabled: 'Enabled',
    synced: 'Synced',
    viewHealthTrends: 'View Health Trends',
    impactSummary: 'Impact Summary',
    totalScreenings: 'Total Screenings Conducted',
    highRiskIdentified: 'High-Risk Cases Identified',
    referralsGenerated: 'Referrals Generated',
    anemiaCasesFlagged: 'Anemia Cases Flagged',
    stepIndicator: 'Step',
    requiredField: 'Required field',
    good: 'Good',
    poor: 'Poor',
    dipAndPlace: 'Dip Strip and Place',
    startTimer: 'Start Timer',
    timerInstruction: 'Dip the strip in urine and place it within the clip. Wait for 90 seconds.',
    secondsRemaining: 'seconds remaining',
    patientCount: 'Patients Screened',
    analyzingImage: 'Analyzing image with AI...',
    skip: 'Skip',
    selectScreeningType: 'Select Screening Type',
    urineAnalysis: 'Urine Analysis',
    bloodAnalysis: 'Blood Analysis',
    bothAnalysis: 'Both (Urine & Blood)',
    captureBloodStrip: 'Capture Blood Strip',
    captureUrineStrip: 'Capture Urine Strip',
    bloodParameters: 'Blood Parameters',
  },
  ta: {
    appName: 'நலம் தேடி லேப்ஸ்',
    tagline: 'கிராமப்புற பெண்களுக்கான மலிவு விலை AI பரிசோதனை',
    startScreening: 'பரிசோதனையைத் தொடங்கு',
    viewReports: 'முந்தைய அறிக்கைகள்',
    about: 'நலம் தேடி பற்றி',
    aboutText: 'நலம் தேடி லேப்ஸ் கிராமப்புற சுகாதாரப் பணியாளர்களுக்கு ஆரம்பத்திலேயே உடல்நல அபாயங்களைக் கண்டறிய AI-மூலம் இயங்கும் பரிசோதனை கருவிகளை வழங்குகிறது.',
    alignStrip: 'ஸ்ட்ரிப்பை பெட்டிக்குள் சீராக வைத்து தெளிவாக புகைப்படம் எடுக்கவும்',
    capture: 'புகைப்படம் எடு',
    processing: 'படம் செயலாக்கப்படுகிறது...',
    results: 'பரிசோதனை முடிவுகள்',
    urineParameters: 'சிறுநீர் அளவுருக்கள்',
    glucose: 'குளுக்கோஸ்',
    protein: 'புரதம்',
    leukocytes: 'லுகோசைட்டுகள்',
    nitrite: 'நைட்ரைட்',
    hemoglobin: 'ஹீமோகுளோபின்',
    hbValue: 'Hb அளவு',
    interpretation: 'விளக்கம்',
    doctorPriority: 'மருத்துவர் வருகை முன்னுரிமை',
    explanation: 'விளக்கம்',
    downloadPdf: 'அறிக்கையைப் பதிவிறக்கவும்',
    shareWhatsapp: 'வாட்ஸ்அப் மூலம் பகிரவும்',
    returnHome: 'முகப்புப் பக்கத்திற்குத் திரும்பு',
    routineVisit: 'வழக்கமான வருகை',
    visitPHC7Days: '7 நாட்களுக்குள் PHC-க்குச் செல்லவும்',
    immediateReferral: 'உடனடி PHC பரிந்துரை',
    disclaimer: 'AI-அடிப்படையிலான பரிசோதனைக் கருவி. இது ஆய்வகத்தால் உறுதிப்படுத்தப்பட்ட நோயறிதல் அல்ல. மருத்துவ மதிப்பீடு தேவை.',
    normal: 'சாதாரணமானது',
    mild: 'மிதமானது',
    high: 'அதிகம்',
    negative: 'இல்லை (Negative)',
    positive: 'உள்ளது (Positive)',
    mildAnemia: 'மிதமான இரத்த சோகை',
    moderateAnemia: 'நடுத்தர இரத்த சோகை',
    severeAnemia: 'கடுமையான இரத்த சோகை',
    enterPhone: 'வாட்ஸ்அப் எண்ணை உள்ளிடவும்',
    phonePlaceholder: 'உதாரணம்: 9876543210',
    continue: 'தொடரவும்',
    previousReports: 'முந்தைய அறிக்கைகள்',
    noReports: 'முந்தைய அறிக்கைகள் எதுவும் இல்லை.',
    patientDetails: 'நோயாளி விவரங்கள்',
    patientName: 'நோயாளி பெயர்',
    age: 'வயது',
    village: 'கிராமம் / ஊர்',
    namePlaceholder: 'முழு பெயரை உள்ளிடவும்',
    agePlaceholder: 'வயதை உள்ளிடவும்',
    villagePlaceholder: 'கிராமத்தின் பெயரை உள்ளிடவும்',
    parameter: 'அளவுரு',
    result: 'முடிவு',
    unit: 'அலகு',
    refRange: 'குறிப்பு வரம்பு',
    labReport: 'ஆய்வக பரிசோதனை அறிக்கை',
    selectSource: 'மூலத்தைத் தேர்ந்தெடுக்கவும்',
    useCamera: 'கேமராவைப் பயன்படுத்தவும்',
    uploadImage: 'படத்தைப் பதிவேற்றவும்',
    lowRisk: 'குறைந்த அபாயம்',
    moderateRisk: 'மிதமான அபாயம்',
    highRisk: 'அதிக அபாயம்',
    criticalRisk: 'மிகவும் ஆபத்தானது',
    aiConfidence: 'AI நம்பிக்கை மதிப்பெண்',
    modelVersion: 'மாதிரி பதிப்பு',
    datasetSize: 'சரிபார்க்கப்பட்ட தரவுத்தொகுப்பு அளவு',
    whyThisDecision: 'இந்த முடிவு ஏன்?',
    testQualityCheck: 'சோதனை தர சரிபார்ப்பு',
    imageQuality: 'படத்தின் தரம்',
    detectionConfidence: 'ஸ்ட்ரிப் கண்டறிதல் நம்பிக்கை',
    lightingCalibration: 'ஒளி அளவுத்திருத்தம்',
    passed: 'வெற்றி',
    failed: 'தோல்வி',
    recommendedAction: 'பரிந்துரைக்கப்பட்ட நடவடிக்கை',
    visitPHC24h: '24 மணி நேரத்திற்குள் PHC-க்குச் செல்லவும்',
    repeatUrineTest: 'சிறுநீர் பரிசோதனையை மீண்டும் செய்யவும்',
    confirmatoryHbTest: 'உறுதிப்படுத்தும் Hb சோதனை',
    ironSupplements: 'உறுதிப்படுத்தப்பட்டால் இரும்புச் சத்து மருந்துகள்',
    doctorConsultationMandatory: 'அதிக அபாயம் உள்ளவர்களுக்கு மருத்துவர் ஆலோசனை கட்டாயம்',
    screeningLocation: 'பரிசோதனை இடம்',
    screenedBy: 'பரிசோதித்தவர்',
    deviceId: 'சாதன ஐடி',
    offlineStatus: 'ஆஃப்லைன் பயன்முறை நிலை',
    enabled: 'செயல்படுத்தப்பட்டது',
    synced: 'ஒத்திசைக்கப்பட்டது',
    viewHealthTrends: 'ஆரோக்கிய போக்குகளைக் காண்க',
    impactSummary: 'தாக்கச் சுருக்கம்',
    totalScreenings: 'நடத்தப்பட்ட மொத்த பரிசோதனைகள்',
    highRiskIdentified: 'கண்டறியப்பட்ட அதிக அபாய வழக்குகள்',
    referralsGenerated: 'உருவாக்கப்பட்ட பரிந்துரைகள்',
    anemiaCasesFlagged: 'இரத்த சோகை வழக்குகள் கண்டறியப்பட்டன',
    stepIndicator: 'படி',
    requiredField: 'தேவையான புலம்',
    good: 'நல்லது',
    poor: 'மோசமானது',
    dipAndPlace: 'துண்டு நனைத்து வைக்கவும்',
    startTimer: 'நேரத்தைத் தொடங்கு',
    timerInstruction: 'துண்டு நனைத்து 90 விநாடிகள் காத்திருக்கவும்',
    secondsRemaining: 'விநாடிகள் மீதமுள்ளன',
    patientCount: 'பரிசோதிக்கப்பட்ட நோயாளிகள்',
    analyzingImage: 'படத்தை ஆய்வு செய்கிறது...',
    skip: 'தவிர்',
    selectScreeningType: 'பரிசோதனை வகையைத் தேர்ந்தெடுக்கவும்',
    urineAnalysis: 'சிறுநீர் பரிசோதனை',
    bloodAnalysis: 'இரத்தப் பரிசோதனை',
    bothAnalysis: 'இரண்டும் (சிறுநீர் மற்றும் இரத்தம்)',
    captureBloodStrip: 'இரத்தப் பரிசோதனை துண்டைப் பிடிக்கவும்',
    captureUrineStrip: 'சிறுநீர் பரிசோதனை துண்டைப் பிடிக்கவும்',
    bloodParameters: 'இரத்த அளவுருக்கள்',
  },
};

export const getExplanation = (data: any, lang: 'en' | 'ta') => {
  if (lang === 'en') {
    if (data.priority === 'Red') {
      return 'The screening results indicate significant abnormalities in urine parameters and a low hemoglobin level. This combination suggests a high risk of infection or other underlying health issues that require immediate medical attention. We strongly advise you to visit the nearest Primary Health Centre (PHC) or a hospital immediately for a comprehensive clinical diagnosis and treatment.';
    } else if (data.priority === 'Yellow') {
      return 'Some of the parameters are slightly outside the normal range, and your hemoglobin level shows signs of mild anemia. While not an emergency, these results should be reviewed by a healthcare professional soon. Please visit your nearest PHC within the next 7 days for a follow-up consultation and further advice on diet and health management.';
    }
    return 'All screened parameters are within the expected normal ranges. Your hemoglobin level is healthy. To maintain this status, continue following a balanced diet rich in iron and nutrients. We recommend regular routine checkups to monitor your long-term health.';
  } else {
    if (data.priority === 'Red') {
      return 'சிறுநீர் அளவுருக்களில் குறிப்பிடத்தக்க மாற்றங்கள் மற்றும் குறைந்த ஹீமோகுளோபின் அளவு ஆகியவை இந்த பரிசோதனை முடிவுகளில் காணப்படுகின்றன. இது தொற்று அல்லது பிற உடல்நலப் பிரச்சினைகளுக்கான அதிக வாய்ப்பைக் குறிக்கிறது, இதற்கு உடனடி மருத்துவ கவனிப்பு தேவை. விரிவான மருத்துவ நோயறிதல் மற்றும் சிகிச்சைக்காக உடனடியாக அருகிலுள்ள ஆரம்ப சுகாதார நிலையத்திற்கு (PHC) அல்லது மருத்துவமனைக்குச் செல்லுமாறு நாங்கள் கடுமையாக அறிவுறுத்துகிறோம்.';
    } else if (data.priority === 'Yellow') {
      return 'சில அளவுருக்கள் சாதாரண வரம்பிற்கு சற்றே வெளியே உள்ளன, மேலும் உங்கள் ஹீமோகுளோபின் அளவு லேசான இரத்த சோகையின் அறிகுறிகளைக் காட்டுகிறது. இது அவசரநிலை இல்லை என்றாலும், இந்த முடிவுகளை விரைவில் ஒரு சுகாதார நிபுணர் ஆய்வு செய்ய வேண்டும். அடுத்த 7 நாட்களுக்குள் உங்கள் அருகிலுள்ள PHC-க்குச் சென்று, உணவு மற்றும் ஆரோக்கிய மேலாண்மை குறித்த மேலதிக ஆலோசனைகளைப் பெறவும்.';
    }
    return 'பரிசோதிக்கப்பட்ட அனைத்து அளவுருக்களும் எதிர்பார்க்கப்படும் சாதாரண வரம்பிற்குள் உள்ளன. உங்கள் ஹீமோகுளோபின் அளவு ஆரோக்கியமாக உள்ளது. இந்த நிலையைத் தக்கவைக்க, இரும்புச்சத்து மற்றும் ஊட்டச்சத்துக்கள் நிறைந்த சீரான உணவைத் தொடர்ந்து உட்கொள்ளுங்கள். உங்கள் நீண்டகால ஆரோக்கியத்தைக் கண்காணிக்க வழக்கமான பரிசோதனைகளை நாங்கள் பரிந்துரைக்கிறோம்.';
  }
};
